In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [6]:
# Load Test data from our github repo
url_test = 'https://raw.githubusercontent.com/tjayada/iANNwTF_Project/main/data/Test.csv'
dataDF_test = pd.read_csv(url_test)

# Load Train data from our github repo
url_train = 'https://raw.githubusercontent.com/tjayada/iANNwTF_Project/main/data/Train.csv'
dataDF_train = pd.read_csv(url_train)

In [8]:
# quick look at the data
dataDF_test.head()

,Place_ID X Date,Date,Place_ID,precipitable_water_entire_atmosphere,relative_humidity_2m_above_ground,specific_humidity_2m_above_ground,temperature_2m_above_ground,u_component_of_wind_10m_above_ground,v_component_of_wind_10m_above_ground,L3_NO2_NO2_column_number_density,...,L3_SO2_sensor_zenith_angle,L3_SO2_solar_azimuth_angle,L3_SO2_solar_zenith_angle,L3_CH4_CH4_column_volume_mixing_ratio_dry_air,L3_CH4_aerosol_height,L3_CH4_aerosol_optical_depth,L3_CH4_sensor_azimuth_angle,L3_CH4_sensor_zenith_angle,L3_CH4_solar_azimuth_angle,L3_CH4_solar_zenith_angle
0,0OS9LVX X 2020-01-02,2020-01-02,0OS9LVX,11.600000,30.200001,0.00409,14.656824,3.956377,0.712605,0.000053,...,1.445658,-95.984984,22.942019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0OS9LVX X 2020-01-03,2020-01-03,0OS9LVX,18.300001,42.900002,0.00595,15.026544,4.230430,0.661892,0.000050,...,34.641758,-95.014908,18.539116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0OS9LVX X 2020-01-04,2020-01-04,0OS9LVX,17.600000,41.299999,0.00590,15.511041,5.245728,1.640559,0.000050,...,55.872276,-94.015418,14.140820,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0OS9LVX X 2020-01-05,2020-01-05,0OS9LVX,15.011948,53.100002,0.00709,14.441858,5.454001,-0.190532,0.000055,...,59.174188,-97.247602,32.730553,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0OS9LVX X 2020-01-06,2020-01-06,0OS9LVX,9.700000,71.599998,0.00808,11.896295,3.511787,-0.279441,0.000055,...,40.925873,-96.057265,28.320527,1831.261597,3229.118652,0.031068,-100.278343,41.84708,-95.910744,28.498789

In [9]:
# quite a few NaN's - what should we do about this ?
# 1. Ignore them, since some functions dont take them into account
# 2. Remove them, but maybe we loose too much information (too many rows) that way

In [10]:
dataDF_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16136 entries, 0 to 16135
Data columns (total 77 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Place_ID X Date                                      16136 non-null  object
 1   Date                                                 16136 non-null  object
 2   Place_ID                                             16136 non-null  object
 3   precipitable_water_entire_atmosphere                 16136 non-null  float64
 4   relative_humidity_2m_above_ground                    16136 non-null  float64
 5   specific_humidity_2m_above_ground                    16136 non-null  float64
 6   temperature_2m_above_ground                          16136 non-null  float64
 7   u_component_of_wind_10m_above_ground                 16136 non-null  float64
 8   v_component_of_wind_10m_above_ground                 16136 non-null  float64
 9   L3_NO2_NO2_column_number_density                     14809 non-null  float64
 10  L3_NO2_NO2_slant_column_number_density               14809 non-null  float64
 11  L3_NO2_absorbing_aerosol_index                       14809 non-null  float64
 12  L3_NO2_cloud_fraction                                14809 non-null  float64
 13  L3_NO2_sensor_altitude                               14809 non-null  float64
 14  L3_NO2_sensor_azimuth_angle                          14809 non-null  float64
 15  L3_NO2_sensor_zenith_angle                           14809 non-null  float64
 16  L3_NO2_solar_azimuth_angle                           14809 non-null  float64
 17  L3_NO2_solar_zenith_angle                            14809 non-null  float64
 18  L3_NO2_stratospheric_NO2_column_number_density       14809 non-null  float64
 19  L3_NO2_tropopause_pressure                           14809 non-null  float64
 20  L3_NO2_tropospheric_NO2_column_number_density        11163 non-null  float64
 21  L3_O3_O3_column_number_density                       15922 non-null  float64
 22  L3_O3_O3_effective_temperature                       15922 non-null  float64
 23  L3_O3_cloud_fraction                                 15922 non-null  float64
 24  L3_O3_sensor_azimuth_angle                           15922 non-null  float64
 25  L3_O3_sensor_zenith_angle                            15922 non-null  float64
 26  L3_O3_solar_azimuth_angle                            15922 non-null  float64
 27  L3_O3_solar_zenith_angle                             15922 non-null  float64
 28  L3_CO_CO_column_number_density                       13135 non-null  float64
 29  L3_CO_H2O_column_number_density                      13135 non-null  float64
 30  L3_CO_cloud_height                                   13135 non-null  float64
 31  L3_CO_sensor_altitude                                13135 non-null  float64
 32  L3_CO_sensor_azimuth_angle                           13135 non-null  float64
 33  L3_CO_sensor_zenith_angle                            13135 non-null  float64
 34  L3_CO_solar_azimuth_angle                            13135 non-null  float64
 35  L3_CO_solar_zenith_angle                             13135 non-null  float64
 36  L3_HCHO_HCHO_slant_column_number_density             11916 non-null  float64
 37  L3_HCHO_cloud_fraction                               11916 non-null  float64
 38  L3_HCHO_sensor_azimuth_angle                         11916 non-null  float64
 39  L3_HCHO_sensor_zenith_angle                          11916 non-null  float64
 40  L3_HCHO_solar_azimuth_angle                          11916 non-null  float64
 41  L3_HCHO_solar_zenith_angle                           11916 non-null  float64
 42  L3_HCHO_tropospheric_HCHO_column_number_density      11916 non-null  float64
 43  L3_HCHO_tropospheric_HCHO_column_number_density_amf  11916 non-null  float64
 44  L3_CLOUD_cloud_base_height                           15186 non-null  float64
 45  L3_CLOUD_cloud_base_pressure                         15186 non-null  float64
 46  L3_CLOUD_cloud_fraction                              15874 non-null  float64
 47  L3_CLOUD_cloud_optical_depth                         15186 non-null  float64
 48  L3_CLOUD_cloud_top_height                            15186 non-null  float64
 49  L3_CLOUD_cloud_top_pressure                          15186 non-null  float64
 50  L3_CLOUD_sensor_azimuth_angle                        15874 non-null  float64
 51  L3_CLOUD_sensor_zenith_angle                         15874 non-null  float64
 52  L3_CLOUD_solar_azimuth_angle                         15874 non-null  float64
 53  L3_CLOUD_solar_zenith_angle                          15874 non-null  float64
 54  L3_CLOUD_surface_albedo                              15186 non-null  float64
 55  L3_AER_AI_absorbing_aerosol_index                    16043 non-null  float64
 56  L3_AER_AI_sensor_altitude                            16043 non-null  float64
 57  L3_AER_AI_sensor_azimuth_angle                       16043 non-null  float64
 58  L3_AER_AI_sensor_zenith_angle                        16043 non-null  float64
 59  L3_AER_AI_solar_azimuth_angle                        16043 non-null  float64
 60  L3_AER_AI_solar_zenith_angle                         16043 non-null  float64
 61  L3_SO2_SO2_column_number_density                     11963 non-null  float64
 62  L3_SO2_SO2_column_number_density_amf                 11963 non-null  float64
 63  L3_SO2_SO2_slant_column_number_density               11963 non-null  float64
 64  L3_SO2_absorbing_aerosol_index                       11934 non-null  float64
 65  L3_SO2_cloud_fraction                                11963 non-null  float64
 66  L3_SO2_sensor_azimuth_angle                          11963 non-null  float64
 67  L3_SO2_sensor_zenith_angle                           11963 non-null  float64
 68  L3_SO2_solar_azimuth_angle                           11963 non-null  float64
 69  L3_SO2_solar_zenith_angle                            11963 non-null  float64
 70  L3_CH4_CH4_column_volume_mixing_ratio_dry_air        3115 non-null   float64
 71  L3_CH4_aerosol_height                                3115 non-null   float64
 72  L3_CH4_aerosol_optical_depth                         3115 non-null   float64
 73  L3_CH4_sensor_azimuth_angle                          3115 non-null   float64
 74  L3_CH4_sensor_zenith_angle                           3115 non-null   float64
 75  L3_CH4_solar_azimuth_angle                           3115 non-null   float64
 76  L3_CH4_solar_zenith_angle                            3115 non-null   float64
dtypes: float64(74), object(3)
memory usage: 9.5+ MB

In [11]:
# 1. need to change date to datetime format
# 2. columns 70 to 76 are consisting mainly of missing data

In [12]:
dataDF_test.describe()

,precipitable_water_entire_atmosphere,relative_humidity_2m_above_ground,specific_humidity_2m_above_ground,temperature_2m_above_ground,u_component_of_wind_10m_above_ground,v_component_of_wind_10m_above_ground,L3_NO2_NO2_column_number_density,L3_NO2_NO2_slant_column_number_density,L3_NO2_absorbing_aerosol_index,L3_NO2_cloud_fraction,...,L3_SO2_sensor_zenith_angle,L3_SO2_solar_azimuth_angle,L3_SO2_solar_zenith_angle,L3_CH4_CH4_column_volume_mixing_ratio_dry_air,L3_CH4_aerosol_height,L3_CH4_aerosol_optical_depth,L3_CH4_sensor_azimuth_angle,L3_CH4_sensor_zenith_angle,L3_CH4_solar_azimuth_angle,L3_CH4_solar_zenith_angle
count,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,14809.000000,14809.000000,14809.000000,14809.000000,...,11963.000000,11963.000000,11963.000000,3115.000000,3115.000000,3115.000000,3115.000000,3115.000000,3115.000000,3115.000000
mean,14.202076,71.136312,0.005513,8.651834,0.660754,0.113826,0.000098,0.000166,-1.089137,0.293308,...,34.894186,-122.992436,49.048986,945.230960,1766.062448,0.018122,0.587431,14.053838,-71.287981,24.113993
std,9.377060,18.357542,0.003261,8.033144,2.854376,2.914895,0.000084,0.000101,0.616871,0.306695,...,18.808611,76.258227,13.809821,930.249966,1755.875373,0.029822,55.802139,18.085361,87.392331,25.099069
min,0.900000,6.700000,0.000279,-26.628958,-15.837668,-14.043520,-0.000031,0.000000,-3.495448,0.000000,...,0.000000,-179.953644,0.000000,0.000000,0.000000,0.000000,-105.016572,0.000000,-179.924887,0.000000
25%,7.655303,60.000000,0.003401,3.201305,-1.040559,-1.590374,0.000059,0.000127,-1.525122,0.029981,...,18.517603,-166.951551,40.406972,0.000000,0.000000,0.000000,0.000000,0.000000,-163.013042,0.000000
50%,11.600000,74.800003,0.004610,7.482545,0.402638,0.043358,0.000079,0.000154,-1.172175,0.172885,...,36.782582,-158.740565,50.105448,1771.898988,2943.639456,0.003386,0.000000,1.538256,0.000000,21.074167
75%,18.100000,85.500000,0.006598,13.834132,2.167810,1.708833,0.000115,0.000191,-0.721279,0.500543,...,51.485177,-124.569494,59.020340,1863.157119,3424.017252,0.025774,62.156588,27.354263,0.000000,48.395878
max,63.100002,100.000000,0.020180,34.851022,19.889325,16.682952,0.001233,0.001343,5.196880,1.000000,...,66.216644,179.884901,79.647072,1992.809481,6196.581543,0.215117,75.897305,59.984665,179.955138,69.925462

In [15]:
# in PCA the features with the highest variance (variance = std^2) are becoming the new feature space, 
# so we should think about reducing our features to the most important once (may not be entirely correct)
# And we need to normalize the data even if we decide against PCA