In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
# Load Test data from our github repo
url_test = 'https://raw.githubusercontent.com/tjayada/iANNwTF_Project/main/data/Test.csv'
dataDF_test = pd.read_csv(url_test)

# Load Train data from our github repo
url_train = 'https://raw.githubusercontent.com/tjayada/iANNwTF_Project/main/data/Train.csv'
dataDF_train = pd.read_csv(url_train)

In [3]:
# quick look at the data
dataDF_train.head()

,Place_ID X Date,Date,Place_ID,target,target_min,target_max,target_variance,target_count,precipitable_water_entire_atmosphere,relative_humidity_2m_above_ground,...,L3_SO2_sensor_zenith_angle,L3_SO2_solar_azimuth_angle,L3_SO2_solar_zenith_angle,L3_CH4_CH4_column_volume_mixing_ratio_dry_air,L3_CH4_aerosol_height,L3_CH4_aerosol_optical_depth,L3_CH4_sensor_azimuth_angle,L3_CH4_sensor_zenith_angle,L3_CH4_solar_azimuth_angle,L3_CH4_solar_zenith_angle
0,010Q650 X 2020-01-02,2020-01-02,010Q650,38.0,23.0,53.0,769.50,92,11.000000,60.200001,...,38.593017,-61.752587,22.363665,1793.793579,3227.855469,0.010579,74.481049,37.501499,-62.142639,22.545118
1,010Q650 X 2020-01-03,2020-01-03,010Q650,39.0,25.0,63.0,1319.85,91,14.600000,48.799999,...,59.624912,-67.693509,28.614804,1789.960449,3384.226562,0.015104,75.630043,55.657486,-53.868134,19.293652
2,010Q650 X 2020-01-04,2020-01-04,010Q650,24.0,8.0,56.0,1181.96,96,16.400000,33.400002,...,49.839714,-78.342701,34.296977,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,010Q650 X 2020-01-05,2020-01-05,010Q650,49.0,10.0,55.0,1113.67,96,6.911948,21.300001,...,29.181258,-73.896588,30.545446,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,010Q650 X 2020-01-06,2020-01-06,010Q650,21.0,9.0,52.0,1164.82,95,13.900001,44.700001,...,0.797294,-68.612480,26.899694,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# quite a few NaN's - what should we do about this ?
# 1. Ignore them, since some functions dont take them into account
# 2. Remove them, but maybe we loose too much information (too many rows) that way

In [5]:
dataDF_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16136 entries, 0 to 16135
Data columns (total 77 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Place_ID X Date                                      16136 non-null  object
 1   Date                                                 16136 non-null  object
 2   Place_ID                                             16136 non-null  object
 3   precipitable_water_entire_atmosphere                 16136 non-null  float64
 4   relative_humidity_2m_above_ground                    16136 non-null  float64
 5   specific_humidity_2m_above_ground                    16136 non-null  float64
 6   temperature_2m_above_ground                          16136 non-null  float64
 7   u_component_of_wind_10m_above_ground                 16136 non-null  float64
 8   v_component_of_wind_10m_above_ground                 16136 non-null  float64
 9   L3_NO2_NO2_column_number_density                     14809 non-null  float64
 10  L3_NO2_NO2_slant_column_number_density               14809 non-null  float64
 11  L3_NO2_absorbing_aerosol_index                       14809 non-null  float64
 12  L3_NO2_cloud_fraction                                14809 non-null  float64
 13  L3_NO2_sensor_altitude                               14809 non-null  float64
 14  L3_NO2_sensor_azimuth_angle                          14809 non-null  float64
 15  L3_NO2_sensor_zenith_angle                           14809 non-null  float64
 16  L3_NO2_solar_azimuth_angle                           14809 non-null  float64
 17  L3_NO2_solar_zenith_angle                            14809 non-null  float64
 18  L3_NO2_stratospheric_NO2_column_number_density       14809 non-null  float64
 19  L3_NO2_tropopause_pressure                           14809 non-null  float64
 20  L3_NO2_tropospheric_NO2_column_number_density        11163 non-null  float64
 21  L3_O3_O3_column_number_density                       15922 non-null  float64
 22  L3_O3_O3_effective_temperature                       15922 non-null  float64
 23  L3_O3_cloud_fraction                                 15922 non-null  float64
 24  L3_O3_sensor_azimuth_angle                           15922 non-null  float64
 25  L3_O3_sensor_zenith_angle                            15922 non-null  float64
 26  L3_O3_solar_azimuth_angle                            15922 non-null  float64
 27  L3_O3_solar_zenith_angle                             15922 non-null  float64
 28  L3_CO_CO_column_number_density                       13135 non-null  float64
 29  L3_CO_H2O_column_number_density                      13135 non-null  float64
 30  L3_CO_cloud_height                                   13135 non-null  float64
 31  L3_CO_sensor_altitude                                13135 non-null  float64
 32  L3_CO_sensor_azimuth_angle                           13135 non-null  float64
 33  L3_CO_sensor_zenith_angle                            13135 non-null  float64
 34  L3_CO_solar_azimuth_angle                            13135 non-null  float64
 35  L3_CO_solar_zenith_angle                             13135 non-null  float64
 36  L3_HCHO_HCHO_slant_column_number_density             11916 non-null  float64
 37  L3_HCHO_cloud_fraction                               11916 non-null  float64
 38  L3_HCHO_sensor_azimuth_angle                         11916 non-null  float64
 39  L3_HCHO_sensor_zenith_angle                          11916 non-null  float64
 40  L3_HCHO_solar_azimuth_angle                          11916 non-null  float64
 41  L3_HCHO_solar_zenith_angle                           11916 non-null  float64
 42  L3_HCHO_tropospheric_HCHO_column_number_density      11916 non-null  float64
 43  L3_HCHO_tropospheric_HCHO_column_number_density_amf  11916 non-null  float64
 44  L3_CLOUD_cloud_base_height                           15186 non-null  float64
 45  L3_CLOUD_cloud_base_pressure                         15186 non-null  float64
 46  L3_CLOUD_cloud_fraction                              15874 non-null  float64
 47  L3_CLOUD_cloud_optical_depth                         15186 non-null  float64
 48  L3_CLOUD_cloud_top_height                            15186 non-null  float64
 49  L3_CLOUD_cloud_top_pressure                          15186 non-null  float64
 50  L3_CLOUD_sensor_azimuth_angle                        15874 non-null  float64
 51  L3_CLOUD_sensor_zenith_angle                         15874 non-null  float64
 52  L3_CLOUD_solar_azimuth_angle                         15874 non-null  float64
 53  L3_CLOUD_solar_zenith_angle                          15874 non-null  float64
 54  L3_CLOUD_surface_albedo                              15186 non-null  float64
 55  L3_AER_AI_absorbing_aerosol_index                    16043 non-null  float64
 56  L3_AER_AI_sensor_altitude                            16043 non-null  float64
 57  L3_AER_AI_sensor_azimuth_angle                       16043 non-null  float64
 58  L3_AER_AI_sensor_zenith_angle                        16043 non-null  float64
 59  L3_AER_AI_solar_azimuth_angle                        16043 non-null  float64
 60  L3_AER_AI_solar_zenith_angle                         16043 non-null  float64
 61  L3_SO2_SO2_column_number_density                     11963 non-null  float64
 62  L3_SO2_SO2_column_number_density_amf                 11963 non-null  float64
 63  L3_SO2_SO2_slant_column_number_density               11963 non-null  float64
 64  L3_SO2_absorbing_aerosol_index                       11934 non-null  float64
 65  L3_SO2_cloud_fraction                                11963 non-null  float64
 66  L3_SO2_sensor_azimuth_angle                          11963 non-null  float64
 67  L3_SO2_sensor_zenith_angle                           11963 non-null  float64
 68  L3_SO2_solar_azimuth_angle                           11963 non-null  float64
 69  L3_SO2_solar_zenith_angle                            11963 non-null  float64
 70  L3_CH4_CH4_column_volume_mixing_ratio_dry_air        3115 non-null   float64
 71  L3_CH4_aerosol_height                                3115 non-null   float64
 72  L3_CH4_aerosol_optical_depth                         3115 non-null   float64
 73  L3_CH4_sensor_azimuth_angle                          3115 non-null   float64
 74  L3_CH4_sensor_zenith_angle                           3115 non-null   float64
 75  L3_CH4_solar_azimuth_angle                           3115 non-null   float64
 76  L3_CH4_solar_zenith_angle                            3115 non-null   float64
dtypes: float64(74), object(3)
memory usage: 9.5+ MB

In [6]:
# 1. need to change date to datetime format
# 2. columns 70 to 76 are consisting mainly of missing data

In [7]:
dataDF_test.describe()

,precipitable_water_entire_atmosphere,relative_humidity_2m_above_ground,specific_humidity_2m_above_ground,temperature_2m_above_ground,u_component_of_wind_10m_above_ground,v_component_of_wind_10m_above_ground,L3_NO2_NO2_column_number_density,L3_NO2_NO2_slant_column_number_density,L3_NO2_absorbing_aerosol_index,L3_NO2_cloud_fraction,...,L3_SO2_sensor_zenith_angle,L3_SO2_solar_azimuth_angle,L3_SO2_solar_zenith_angle,L3_CH4_CH4_column_volume_mixing_ratio_dry_air,L3_CH4_aerosol_height,L3_CH4_aerosol_optical_depth,L3_CH4_sensor_azimuth_angle,L3_CH4_sensor_zenith_angle,L3_CH4_solar_azimuth_angle,L3_CH4_solar_zenith_angle
count,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,14809.000000,14809.000000,14809.000000,14809.000000,...,11963.000000,11963.000000,11963.000000,3115.000000,3115.000000,3115.000000,3115.000000,3115.000000,3115.000000,3115.000000
mean,14.202076,71.136312,0.005513,8.651834,0.660754,0.113826,0.000098,0.000166,-1.089137,0.293308,...,34.894186,-122.992436,49.048986,945.230960,1766.062448,0.018122,0.587431,14.053838,-71.287981,24.113993
std,9.377060,18.357542,0.003261,8.033144,2.854376,2.914895,0.000084,0.000101,0.616871,0.306695,...,18.808611,76.258227,13.809821,930.249966,1755.875373,0.029822,55.802139,18.085361,87.392331,25.099069
min,0.900000,6.700000,0.000279,-26.628958,-15.837668,-14.043520,-0.000031,0.000000,-3.495448,0.000000,...,0.000000,-179.953644,0.000000,0.000000,0.000000,0.000000,-105.016572,0.000000,-179.924887,0.000000
25%,7.655303,60.000000,0.003401,3.201305,-1.040559,-1.590374,0.000059,0.000127,-1.525122,0.029981,...,18.517603,-166.951551,40.406972,0.000000,0.000000,0.000000,0.000000,0.000000,-163.013042,0.000000
50%,11.600000,74.800003,0.004610,7.482545,0.402638,0.043358,0.000079,0.000154,-1.172175,0.172885,...,36.782582,-158.740565,50.105448,1771.898988,2943.639456,0.003386,0.000000,1.538256,0.000000,21.074167
75%,18.100000,85.500000,0.006598,13.834132,2.167810,1.708833,0.000115,0.000191,-0.721279,0.500543,...,51.485177,-124.569494,59.020340,1863.157119,3424.017252,0.025774,62.156588,27.354263,0.000000,48.395878
max,63.100002,100.000000,0.020180,34.851022,19.889325,16.682952,0.001233,0.001343,5.196880,1.000000,...,66.216644,179.884901,79.647072,1992.809481,6196.581543,0.215117,75.897305,59.984665,179.955138,69.925462

In [8]:
# in PCA the features with the highest variance (variance = std^2) are becoming the new feature space, 
# so we should think about reducing our features to the most important once (may not be entirely correct)
# And we need to normalize the data even if we decide against PCA

In [9]:
# first approach:
# remove every row with NaN's

first_try_test = dataDF_test
first_try_test = first_try_test.dropna()

first_try_test.info()

# only 2039 rows are left

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2039 entries, 4 to 16134
Data columns (total 77 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Place_ID X Date                                      2039 non-null   object
 1   Date                                                 2039 non-null   object
 2   Place_ID                                             2039 non-null   object
 3   precipitable_water_entire_atmosphere                 2039 non-null   float64
 4   relative_humidity_2m_above_ground                    2039 non-null   float64
 5   specific_humidity_2m_above_ground                    2039 non-null   float64
 6   temperature_2m_above_ground                          2039 non-null   float64
 7   u_component_of_wind_10m_above_ground                 2039 non-null   float64
 8   v_component_of_wind_10m_above_ground                 2039 non-null   float64
 9   L3_NO2_NO2_column_number_density                     2039 non-null   float64
 10  L3_NO2_NO2_slant_column_number_density               2039 non-null   float64
 11  L3_NO2_absorbing_aerosol_index                       2039 non-null   float64
 12  L3_NO2_cloud_fraction                                2039 non-null   float64
 13  L3_NO2_sensor_altitude                               2039 non-null   float64
 14  L3_NO2_sensor_azimuth_angle                          2039 non-null   float64
 15  L3_NO2_sensor_zenith_angle                           2039 non-null   float64
 16  L3_NO2_solar_azimuth_angle                           2039 non-null   float64
 17  L3_NO2_solar_zenith_angle                            2039 non-null   float64
 18  L3_NO2_stratospheric_NO2_column_number_density       2039 non-null   float64
 19  L3_NO2_tropopause_pressure                           2039 non-null   float64
 20  L3_NO2_tropospheric_NO2_column_number_density        2039 non-null   float64
 21  L3_O3_O3_column_number_density                       2039 non-null   float64
 22  L3_O3_O3_effective_temperature                       2039 non-null   float64
 23  L3_O3_cloud_fraction                                 2039 non-null   float64
 24  L3_O3_sensor_azimuth_angle                           2039 non-null   float64
 25  L3_O3_sensor_zenith_angle                            2039 non-null   float64
 26  L3_O3_solar_azimuth_angle                            2039 non-null   float64
 27  L3_O3_solar_zenith_angle                             2039 non-null   float64
 28  L3_CO_CO_column_number_density                       2039 non-null   float64
 29  L3_CO_H2O_column_number_density                      2039 non-null   float64
 30  L3_CO_cloud_height                                   2039 non-null   float64
 31  L3_CO_sensor_altitude                                2039 non-null   float64
 32  L3_CO_sensor_azimuth_angle                           2039 non-null   float64
 33  L3_CO_sensor_zenith_angle                            2039 non-null   float64
 34  L3_CO_solar_azimuth_angle                            2039 non-null   float64
 35  L3_CO_solar_zenith_angle                             2039 non-null   float64
 36  L3_HCHO_HCHO_slant_column_number_density             2039 non-null   float64
 37  L3_HCHO_cloud_fraction                               2039 non-null   float64
 38  L3_HCHO_sensor_azimuth_angle                         2039 non-null   float64
 39  L3_HCHO_sensor_zenith_angle                          2039 non-null   float64
 40  L3_HCHO_solar_azimuth_angle                          2039 non-null   float64
 41  L3_HCHO_solar_zenith_angle                           2039 non-null   float64
 42  L3_HCHO_tropospheric_HCHO_column_number_density      2039 non-null   float64
 43  L3_HCHO_tropospheric_HCHO_column_number_density_amf  2039 non-null   float64
 44  L3_CLOUD_cloud_base_height                           2039 non-null   float64
 45  L3_CLOUD_cloud_base_pressure                         2039 non-null   float64
 46  L3_CLOUD_cloud_fraction                              2039 non-null   float64
 47  L3_CLOUD_cloud_optical_depth                         2039 non-null   float64
 48  L3_CLOUD_cloud_top_height                            2039 non-null   float64
 49  L3_CLOUD_cloud_top_pressure                          2039 non-null   float64
 50  L3_CLOUD_sensor_azimuth_angle                        2039 non-null   float64
 51  L3_CLOUD_sensor_zenith_angle                         2039 non-null   float64
 52  L3_CLOUD_solar_azimuth_angle                         2039 non-null   float64
 53  L3_CLOUD_solar_zenith_angle                          2039 non-null   float64
 54  L3_CLOUD_surface_albedo                              2039 non-null   float64
 55  L3_AER_AI_absorbing_aerosol_index                    2039 non-null   float64
 56  L3_AER_AI_sensor_altitude                            2039 non-null   float64
 57  L3_AER_AI_sensor_azimuth_angle                       2039 non-null   float64
 58  L3_AER_AI_sensor_zenith_angle                        2039 non-null   float64
 59  L3_AER_AI_solar_azimuth_angle                        2039 non-null   float64
 60  L3_AER_AI_solar_zenith_angle                         2039 non-null   float64
 61  L3_SO2_SO2_column_number_density                     2039 non-null   float64
 62  L3_SO2_SO2_column_number_density_amf                 2039 non-null   float64
 63  L3_SO2_SO2_slant_column_number_density               2039 non-null   float64
 64  L3_SO2_absorbing_aerosol_index                       2039 non-null   float64
 65  L3_SO2_cloud_fraction                                2039 non-null   float64
 66  L3_SO2_sensor_azimuth_angle                          2039 non-null   float64
 67  L3_SO2_sensor_zenith_angle                           2039 non-null   float64
 68  L3_SO2_solar_azimuth_angle                           2039 non-null   float64
 69  L3_SO2_solar_zenith_angle                            2039 non-null   float64
 70  L3_CH4_CH4_column_volume_mixing_ratio_dry_air        2039 non-null   float64
 71  L3_CH4_aerosol_height                                2039 non-null   float64
 72  L3_CH4_aerosol_optical_depth                         2039 non-null   float64
 73  L3_CH4_sensor_azimuth_angle                          2039 non-null   float64
 74  L3_CH4_sensor_zenith_angle                           2039 non-null   float64
 75  L3_CH4_solar_azimuth_angle                           2039 non-null   float64
 76  L3_CH4_solar_zenith_angle                            2039 non-null   float64
dtypes: float64(74), object(3)
memory usage: 1.2+ MB

In [10]:
# second approach remove columns 70 - 76 and after that remove everything with NaN's
# since most of these features are missing anyways (>60% of data)

second_try_test = dataDF_test
second_try_test = second_try_test.drop(["L3_CH4_CH4_column_volume_mixing_ratio_dry_air", "L3_CH4_aerosol_height", "L3_CH4_aerosol_optical_depth",
                                      "L3_CH4_sensor_azimuth_angle", "L3_CH4_sensor_zenith_angle", "L3_CH4_solar_azimuth_angle", "L3_CH4_solar_zenith_angle"], axis=1)
second_try_test = second_try_test.dropna()
second_try_test.info()

# we now have 9101 rows left, so three times more than if we just remove everything with NaN

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9101 entries, 0 to 16134
Data columns (total 70 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Place_ID X Date                                      9101 non-null   object
 1   Date                                                 9101 non-null   object
 2   Place_ID                                             9101 non-null   object
 3   precipitable_water_entire_atmosphere                 9101 non-null   float64
 4   relative_humidity_2m_above_ground                    9101 non-null   float64
 5   specific_humidity_2m_above_ground                    9101 non-null   float64
 6   temperature_2m_above_ground                          9101 non-null   float64
 7   u_component_of_wind_10m_above_ground                 9101 non-null   float64
 8   v_component_of_wind_10m_above_ground                 9101 non-null   float64
 9   L3_NO2_NO2_column_number_density                     9101 non-null   float64
 10  L3_NO2_NO2_slant_column_number_density               9101 non-null   float64
 11  L3_NO2_absorbing_aerosol_index                       9101 non-null   float64
 12  L3_NO2_cloud_fraction                                9101 non-null   float64
 13  L3_NO2_sensor_altitude                               9101 non-null   float64
 14  L3_NO2_sensor_azimuth_angle                          9101 non-null   float64
 15  L3_NO2_sensor_zenith_angle                           9101 non-null   float64
 16  L3_NO2_solar_azimuth_angle                           9101 non-null   float64
 17  L3_NO2_solar_zenith_angle                            9101 non-null   float64
 18  L3_NO2_stratospheric_NO2_column_number_density       9101 non-null   float64
 19  L3_NO2_tropopause_pressure                           9101 non-null   float64
 20  L3_NO2_tropospheric_NO2_column_number_density        9101 non-null   float64
 21  L3_O3_O3_column_number_density                       9101 non-null   float64
 22  L3_O3_O3_effective_temperature                       9101 non-null   float64
 23  L3_O3_cloud_fraction                                 9101 non-null   float64
 24  L3_O3_sensor_azimuth_angle                           9101 non-null   float64
 25  L3_O3_sensor_zenith_angle                            9101 non-null   float64
 26  L3_O3_solar_azimuth_angle                            9101 non-null   float64
 27  L3_O3_solar_zenith_angle                             9101 non-null   float64
 28  L3_CO_CO_column_number_density                       9101 non-null   float64
 29  L3_CO_H2O_column_number_density                      9101 non-null   float64
 30  L3_CO_cloud_height                                   9101 non-null   float64
 31  L3_CO_sensor_altitude                                9101 non-null   float64
 32  L3_CO_sensor_azimuth_angle                           9101 non-null   float64
 33  L3_CO_sensor_zenith_angle                            9101 non-null   float64
 34  L3_CO_solar_azimuth_angle                            9101 non-null   float64
 35  L3_CO_solar_zenith_angle                             9101 non-null   float64
 36  L3_HCHO_HCHO_slant_column_number_density             9101 non-null   float64
 37  L3_HCHO_cloud_fraction                               9101 non-null   float64
 38  L3_HCHO_sensor_azimuth_angle                         9101 non-null   float64
 39  L3_HCHO_sensor_zenith_angle                          9101 non-null   float64
 40  L3_HCHO_solar_azimuth_angle                          9101 non-null   float64
 41  L3_HCHO_solar_zenith_angle                           9101 non-null   float64
 42  L3_HCHO_tropospheric_HCHO_column_number_density      9101 non-null   float64
 43  L3_HCHO_tropospheric_HCHO_column_number_density_amf  9101 non-null   float64
 44  L3_CLOUD_cloud_base_height                           9101 non-null   float64
 45  L3_CLOUD_cloud_base_pressure                         9101 non-null   float64
 46  L3_CLOUD_cloud_fraction                              9101 non-null   float64
 47  L3_CLOUD_cloud_optical_depth                         9101 non-null   float64
 48  L3_CLOUD_cloud_top_height                            9101 non-null   float64
 49  L3_CLOUD_cloud_top_pressure                          9101 non-null   float64
 50  L3_CLOUD_sensor_azimuth_angle                        9101 non-null   float64
 51  L3_CLOUD_sensor_zenith_angle                         9101 non-null   float64
 52  L3_CLOUD_solar_azimuth_angle                         9101 non-null   float64
 53  L3_CLOUD_solar_zenith_angle                          9101 non-null   float64
 54  L3_CLOUD_surface_albedo                              9101 non-null   float64
 55  L3_AER_AI_absorbing_aerosol_index                    9101 non-null   float64
 56  L3_AER_AI_sensor_altitude                            9101 non-null   float64
 57  L3_AER_AI_sensor_azimuth_angle                       9101 non-null   float64
 58  L3_AER_AI_sensor_zenith_angle                        9101 non-null   float64
 59  L3_AER_AI_solar_azimuth_angle                        9101 non-null   float64
 60  L3_AER_AI_solar_zenith_angle                         9101 non-null   float64
 61  L3_SO2_SO2_column_number_density                     9101 non-null   float64
 62  L3_SO2_SO2_column_number_density_amf                 9101 non-null   float64
 63  L3_SO2_SO2_slant_column_number_density               9101 non-null   float64
 64  L3_SO2_absorbing_aerosol_index                       9101 non-null   float64
 65  L3_SO2_cloud_fraction                                9101 non-null   float64
 66  L3_SO2_sensor_azimuth_angle                          9101 non-null   float64
 67  L3_SO2_sensor_zenith_angle                           9101 non-null   float64
 68  L3_SO2_solar_azimuth_angle                           9101 non-null   float64
 69  L3_SO2_solar_zenith_angle                            9101 non-null   float64
dtypes: float64(67), object(3)
memory usage: 4.9+ MB

In [11]:
# third approach: replace the NaN's with mean of the column it is in

third_try_test = dataDF_test
third_try_test = third_try_test.fillna(third_try_test.mean())
third_try_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16136 entries, 0 to 16135
Data columns (total 77 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Place_ID X Date                                      16136 non-null  object
 1   Date                                                 16136 non-null  object
 2   Place_ID                                             16136 non-null  object
 3   precipitable_water_entire_atmosphere                 16136 non-null  float64
 4   relative_humidity_2m_above_ground                    16136 non-null  float64
 5   specific_humidity_2m_above_ground                    16136 non-null  float64
 6   temperature_2m_above_ground                          16136 non-null  float64
 7   u_component_of_wind_10m_above_ground                 16136 non-null  float64
 8   v_component_of_wind_10m_above_ground                 16136 non-null  float64
 9   L3_NO2_NO2_column_number_density                     16136 non-null  float64
 10  L3_NO2_NO2_slant_column_number_density               16136 non-null  float64
 11  L3_NO2_absorbing_aerosol_index                       16136 non-null  float64
 12  L3_NO2_cloud_fraction                                16136 non-null  float64
 13  L3_NO2_sensor_altitude                               16136 non-null  float64
 14  L3_NO2_sensor_azimuth_angle                          16136 non-null  float64
 15  L3_NO2_sensor_zenith_angle                           16136 non-null  float64
 16  L3_NO2_solar_azimuth_angle                           16136 non-null  float64
 17  L3_NO2_solar_zenith_angle                            16136 non-null  float64
 18  L3_NO2_stratospheric_NO2_column_number_density       16136 non-null  float64
 19  L3_NO2_tropopause_pressure                           16136 non-null  float64
 20  L3_NO2_tropospheric_NO2_column_number_density        16136 non-null  float64
 21  L3_O3_O3_column_number_density                       16136 non-null  float64
 22  L3_O3_O3_effective_temperature                       16136 non-null  float64
 23  L3_O3_cloud_fraction                                 16136 non-null  float64
 24  L3_O3_sensor_azimuth_angle                           16136 non-null  float64
 25  L3_O3_sensor_zenith_angle                            16136 non-null  float64
 26  L3_O3_solar_azimuth_angle                            16136 non-null  float64
 27  L3_O3_solar_zenith_angle                             16136 non-null  float64
 28  L3_CO_CO_column_number_density                       16136 non-null  float64
 29  L3_CO_H2O_column_number_density                      16136 non-null  float64
 30  L3_CO_cloud_height                                   16136 non-null  float64
 31  L3_CO_sensor_altitude                                16136 non-null  float64
 32  L3_CO_sensor_azimuth_angle                           16136 non-null  float64
 33  L3_CO_sensor_zenith_angle                            16136 non-null  float64
 34  L3_CO_solar_azimuth_angle                            16136 non-null  float64
 35  L3_CO_solar_zenith_angle                             16136 non-null  float64
 36  L3_HCHO_HCHO_slant_column_number_density             16136 non-null  float64
 37  L3_HCHO_cloud_fraction                               16136 non-null  float64
 38  L3_HCHO_sensor_azimuth_angle                         16136 non-null  float64
 39  L3_HCHO_sensor_zenith_angle                          16136 non-null  float64
 40  L3_HCHO_solar_azimuth_angle                          16136 non-null  float64
 41  L3_HCHO_solar_zenith_angle                           16136 non-null  float64
 42  L3_HCHO_tropospheric_HCHO_column_number_density      16136 non-null  float64
 43  L3_HCHO_tropospheric_HCHO_column_number_density_amf  16136 non-null  float64
 44  L3_CLOUD_cloud_base_height                           16136 non-null  float64
 45  L3_CLOUD_cloud_base_pressure                         16136 non-null  float64
 46  L3_CLOUD_cloud_fraction                              16136 non-null  float64
 47  L3_CLOUD_cloud_optical_depth                         16136 non-null  float64
 48  L3_CLOUD_cloud_top_height                            16136 non-null  float64
 49  L3_CLOUD_cloud_top_pressure                          16136 non-null  float64
 50  L3_CLOUD_sensor_azimuth_angle                        16136 non-null  float64
 51  L3_CLOUD_sensor_zenith_angle                         16136 non-null  float64
 52  L3_CLOUD_solar_azimuth_angle                         16136 non-null  float64
 53  L3_CLOUD_solar_zenith_angle                          16136 non-null  float64
 54  L3_CLOUD_surface_albedo                              16136 non-null  float64
 55  L3_AER_AI_absorbing_aerosol_index                    16136 non-null  float64
 56  L3_AER_AI_sensor_altitude                            16136 non-null  float64
 57  L3_AER_AI_sensor_azimuth_angle                       16136 non-null  float64
 58  L3_AER_AI_sensor_zenith_angle                        16136 non-null  float64
 59  L3_AER_AI_solar_azimuth_angle                        16136 non-null  float64
 60  L3_AER_AI_solar_zenith_angle                         16136 non-null  float64
 61  L3_SO2_SO2_column_number_density                     16136 non-null  float64
 62  L3_SO2_SO2_column_number_density_amf                 16136 non-null  float64
 63  L3_SO2_SO2_slant_column_number_density               16136 non-null  float64
 64  L3_SO2_absorbing_aerosol_index                       16136 non-null  float64
 65  L3_SO2_cloud_fraction                                16136 non-null  float64
 66  L3_SO2_sensor_azimuth_angle                          16136 non-null  float64
 67  L3_SO2_sensor_zenith_angle                           16136 non-null  float64
 68  L3_SO2_solar_azimuth_angle                           16136 non-null  float64
 69  L3_SO2_solar_zenith_angle                            16136 non-null  float64
 70  L3_CH4_CH4_column_volume_mixing_ratio_dry_air        16136 non-null  float64
 71  L3_CH4_aerosol_height                                16136 non-null  float64
 72  L3_CH4_aerosol_optical_depth                         16136 non-null  float64
 73  L3_CH4_sensor_azimuth_angle                          16136 non-null  float64
 74  L3_CH4_sensor_zenith_angle                           16136 non-null  float64
 75  L3_CH4_solar_azimuth_angle                           16136 non-null  float64
 76  L3_CH4_solar_zenith_angle                            16136 non-null  float64
dtypes: float64(74), object(3)
memory usage: 9.5+ MB

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  after removing the cwd from sys.path.

In [12]:
first_try_test.describe()

,precipitable_water_entire_atmosphere,relative_humidity_2m_above_ground,specific_humidity_2m_above_ground,temperature_2m_above_ground,u_component_of_wind_10m_above_ground,v_component_of_wind_10m_above_ground,L3_NO2_NO2_column_number_density,L3_NO2_NO2_slant_column_number_density,L3_NO2_absorbing_aerosol_index,L3_NO2_cloud_fraction,...,L3_SO2_sensor_zenith_angle,L3_SO2_solar_azimuth_angle,L3_SO2_solar_zenith_angle,L3_CH4_CH4_column_volume_mixing_ratio_dry_air,L3_CH4_aerosol_height,L3_CH4_aerosol_optical_depth,L3_CH4_sensor_azimuth_angle,L3_CH4_sensor_zenith_angle,L3_CH4_solar_azimuth_angle,L3_CH4_solar_zenith_angle
count,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,...,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000
mean,12.295573,65.222123,0.005306,9.278130,0.347276,-0.309702,0.000110,0.000198,-1.103032,0.086211,...,30.426777,-125.908126,47.084628,1114.061965,2093.917590,0.021730,-4.802573,17.654256,-81.693077,28.581065
std,8.400455,19.520049,0.003341,8.640122,2.381939,2.421176,0.000091,0.000134,0.584995,0.137737,...,19.475571,68.725176,17.885667,913.286346,1739.678154,0.031822,61.686158,19.276451,91.081902,24.918534
min,1.600000,7.042857,0.000425,-22.737875,-8.445196,-10.557734,0.000000,0.000000,-2.423789,0.000000,...,0.000000,-179.741905,0.000000,0.000000,0.000000,0.000000,-105.016572,0.000000,-179.924887,0.000000
25%,6.525864,52.800000,0.003066,2.750940,-0.967443,-1.676034,0.000063,0.000141,-1.516613,0.009682,...,13.780893,-166.423179,39.896162,0.000000,0.000000,0.000000,-90.972777,0.000000,-163.645931,0.000000
50%,9.800000,67.599998,0.004335,8.176843,0.238848,-0.349332,0.000086,0.000175,-1.253977,0.032611,...,31.439629,-159.972017,50.647721,1843.819617,3189.766602,0.010116,0.000000,10.314793,-139.592539,36.080711
75%,15.664739,80.494444,0.006351,15.862684,1.622446,0.923335,0.000136,0.000232,-0.781444,0.084006,...,48.033597,-124.224583,59.338736,1868.855677,3510.174363,0.031169,62.383499,33.555386,0.000000,50.580284
max,55.000000,99.200005,0.019170,29.812555,15.544065,11.191879,0.000644,0.000971,0.876013,0.997532,...,65.103913,179.811188,79.578136,1992.809481,6196.581543,0.215117,75.734833,59.983631,179.955138,69.925462

In [13]:
second_try_test.describe()

,precipitable_water_entire_atmosphere,relative_humidity_2m_above_ground,specific_humidity_2m_above_ground,temperature_2m_above_ground,u_component_of_wind_10m_above_ground,v_component_of_wind_10m_above_ground,L3_NO2_NO2_column_number_density,L3_NO2_NO2_slant_column_number_density,L3_NO2_absorbing_aerosol_index,L3_NO2_cloud_fraction,...,L3_AER_AI_solar_zenith_angle,L3_SO2_SO2_column_number_density,L3_SO2_SO2_column_number_density_amf,L3_SO2_SO2_slant_column_number_density,L3_SO2_absorbing_aerosol_index,L3_SO2_cloud_fraction,L3_SO2_sensor_azimuth_angle,L3_SO2_sensor_zenith_angle,L3_SO2_solar_azimuth_angle,L3_SO2_solar_zenith_angle
count,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,...,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000
mean,13.545015,67.540951,0.005640,9.537998,0.690817,-0.135686,0.000101,0.000181,-1.174016,0.161284,...,48.982314,0.000116,0.395775,0.000031,-1.942863,0.187126,-17.001803,35.287019,-121.188050,48.378077
std,9.293364,18.628499,0.003501,8.417968,2.801859,2.745646,0.000085,0.000112,0.587312,0.177127,...,12.394103,0.000759,0.206861,0.000137,0.666751,0.138613,73.146460,18.713055,73.561766,13.755792
min,0.900000,6.700000,0.000279,-26.628958,-11.969196,-12.519441,-0.000014,0.000000,-2.836539,0.000000,...,9.718456,-0.022437,0.000000,-0.002904,-5.017214,0.000000,-110.301204,0.000000,-179.920889,0.000000
25%,7.100000,55.600002,0.003305,3.587015,-0.932275,-1.721616,0.000060,0.000134,-1.570842,0.025645,...,40.186776,-0.000098,0.247516,-0.000037,-2.354593,0.069952,-97.734002,19.051913,-165.876219,39.911348
50%,10.900001,70.414288,0.004610,8.485856,0.445283,-0.154441,0.000078,0.000164,-1.265444,0.088288,...,49.485713,0.000066,0.355467,0.000026,-1.959030,0.160497,-15.496659,37.805677,-157.658451,49.455743
75%,17.300001,82.100004,0.006920,15.460901,2.134065,1.369988,0.000118,0.000206,-0.877250,0.253959,...,58.050612,0.000286,0.509404,0.000096,-1.587108,0.296633,68.495587,51.881575,-90.224456,58.072131
max,61.218544,99.733336,0.020180,33.363245,16.399620,16.682952,0.001117,0.001343,2.181814,1.000000,...,81.227025,0.009279,1.654503,0.001446,2.256666,0.602902,78.069985,66.063805,179.811188,79.630888

In [14]:
third_try_test.describe()

,precipitable_water_entire_atmosphere,relative_humidity_2m_above_ground,specific_humidity_2m_above_ground,temperature_2m_above_ground,u_component_of_wind_10m_above_ground,v_component_of_wind_10m_above_ground,L3_NO2_NO2_column_number_density,L3_NO2_NO2_slant_column_number_density,L3_NO2_absorbing_aerosol_index,L3_NO2_cloud_fraction,...,L3_SO2_sensor_zenith_angle,L3_SO2_solar_azimuth_angle,L3_SO2_solar_zenith_angle,L3_CH4_CH4_column_volume_mixing_ratio_dry_air,L3_CH4_aerosol_height,L3_CH4_aerosol_optical_depth,L3_CH4_sensor_azimuth_angle,L3_CH4_sensor_zenith_angle,L3_CH4_solar_azimuth_angle,L3_CH4_solar_zenith_angle
count,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,...,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000,16136.000000
mean,14.202076,71.136312,0.005513,8.651834,0.660754,0.113826,0.000098,0.000166,-1.089137,0.293308,...,34.894186,-122.992436,49.048986,945.230960,1766.062448,0.018122,0.587431,14.053838,-71.287981,24.113993
std,9.377060,18.357542,0.003261,8.033144,2.854376,2.914895,0.000080,0.000097,0.590960,0.293813,...,16.194746,65.660490,11.890646,408.671622,771.380235,0.013101,24.514648,7.945148,38.392655,11.026367
min,0.900000,6.700000,0.000279,-26.628958,-15.837668,-14.043520,-0.000031,0.000000,-3.495448,0.000000,...,0.000000,-179.953644,0.000000,0.000000,0.000000,0.000000,-105.016572,0.000000,-179.924887,0.000000
25%,7.655303,60.000000,0.003401,3.201305,-1.040559,-1.590374,0.000061,0.000129,-1.494288,0.035840,...,25.474730,-164.097459,44.177145,945.230960,1766.062448,0.018122,0.587431,14.053838,-71.287981,24.113993
50%,11.600000,74.800003,0.004610,7.482545,0.402638,0.043358,0.000083,0.000160,-1.104627,0.217236,...,34.894186,-147.742835,49.048986,945.230960,1766.062448,0.018122,0.587431,14.053838,-71.287981,24.113993
75%,18.100000,85.500000,0.006598,13.834132,2.167810,1.708833,0.000110,0.000186,-0.773947,0.460714,...,47.302635,-122.992436,55.838812,945.230960,1766.062448,0.018122,0.587431,14.053838,-71.287981,24.113993
max,63.100002,100.000000,0.020180,34.851022,19.889325,16.682952,0.001233,0.001343,5.196880,1.000000,...,66.216644,179.884901,79.647072,1992.809481,6196.581543,0.215117,75.897305,59.984665,179.955138,69.925462

In [15]:
# huge differences in first approach compared to second and third one.
# -> first is even worse in changing the "meaning" of the data than actually "inventing" new data like we did in the third approach

# from now on only keep on working with second and third approach

In [16]:
# we also need to normalize the data:

x = second_try_test.iloc[:,3:]
second_try_test.iloc[:,3:] = (x-x.min())/ (x.max() - x.min())

y = third_try_test.iloc[:,3:]
third_try_test.iloc[:,3:] = (y-y.min())/ (y.max() - y.min())

In [17]:
second_try_test.describe()

,precipitable_water_entire_atmosphere,relative_humidity_2m_above_ground,specific_humidity_2m_above_ground,temperature_2m_above_ground,u_component_of_wind_10m_above_ground,v_component_of_wind_10m_above_ground,L3_NO2_NO2_column_number_density,L3_NO2_NO2_slant_column_number_density,L3_NO2_absorbing_aerosol_index,L3_NO2_cloud_fraction,...,L3_AER_AI_solar_zenith_angle,L3_SO2_SO2_column_number_density,L3_SO2_SO2_column_number_density_amf,L3_SO2_SO2_slant_column_number_density,L3_SO2_absorbing_aerosol_index,L3_SO2_cloud_fraction,L3_SO2_sensor_azimuth_angle,L3_SO2_sensor_zenith_angle,L3_SO2_solar_azimuth_angle,L3_SO2_solar_zenith_angle
count,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,...,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000,9101.000000
mean,0.209637,0.653969,0.269401,0.602861,0.446265,0.424066,0.101114,0.134870,0.331289,0.161284,...,0.549079,0.711086,0.239211,0.674781,0.422656,0.310376,0.495295,0.534135,0.163268,0.607529
std,0.154071,0.200235,0.175920,0.140318,0.098765,0.094021,0.075161,0.083334,0.117033,0.177127,...,0.173323,0.023936,0.125029,0.031539,0.091664,0.229910,0.388310,0.283257,0.204490,0.172744
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.102788,0.525618,0.152088,0.503665,0.389051,0.369758,0.065048,0.099979,0.252214,0.025645,...,0.426079,0.704344,0.149601,0.659169,0.366052,0.116025,0.066715,0.288387,0.039042,0.501204
50%,0.165787,0.684854,0.217652,0.585323,0.437610,0.423424,0.081391,0.122082,0.313070,0.088288,...,0.556119,0.709511,0.214848,0.673517,0.420434,0.266207,0.503286,0.572260,0.061886,0.621062
75%,0.271890,0.810462,0.333716,0.701589,0.497140,0.475626,0.116101,0.153284,0.390425,0.253959,...,0.675893,0.716448,0.307889,0.689633,0.471565,0.492009,0.949173,0.785325,0.249342,0.729266
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [18]:
# to do:
# - one hot encode places (?)
# - convert date to datetime
# do the same to the training set and also remove the targets

# create copies and instead of datetime use weekdays or stuff like that

In [19]:
# second approach remove columns 70 - 76 and after that remove everything with NaN's
# since most of these features are missing anyways (>60% of data)

second_try_train = dataDF_train
second_try_train = second_try_train.drop(["L3_CH4_CH4_column_volume_mixing_ratio_dry_air", "L3_CH4_aerosol_height", "L3_CH4_aerosol_optical_depth",
                                      "L3_CH4_sensor_azimuth_angle", "L3_CH4_sensor_zenith_angle", "L3_CH4_solar_azimuth_angle", "L3_CH4_solar_zenith_angle"], axis=1)
second_try_train = second_try_train.dropna()
second_try_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18219 entries, 1 to 30555
Data columns (total 75 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Place_ID X Date                                      18219 non-null  object
 1   Date                                                 18219 non-null  object
 2   Place_ID                                             18219 non-null  object
 3   target                                               18219 non-null  float64
 4   target_min                                           18219 non-null  float64
 5   target_max                                           18219 non-null  float64
 6   target_variance                                      18219 non-null  float64
 7   target_count                                         18219 non-null  int64
 8   precipitable_water_entire_atmosphere                 18219 non-null  float64
 9   relative_humidity_2m_above_ground                    18219 non-null  float64
 10  specific_humidity_2m_above_ground                    18219 non-null  float64
 11  temperature_2m_above_ground                          18219 non-null  float64
 12  u_component_of_wind_10m_above_ground                 18219 non-null  float64
 13  v_component_of_wind_10m_above_ground                 18219 non-null  float64
 14  L3_NO2_NO2_column_number_density                     18219 non-null  float64
 15  L3_NO2_NO2_slant_column_number_density               18219 non-null  float64
 16  L3_NO2_absorbing_aerosol_index                       18219 non-null  float64
 17  L3_NO2_cloud_fraction                                18219 non-null  float64
 18  L3_NO2_sensor_altitude                               18219 non-null  float64
 19  L3_NO2_sensor_azimuth_angle                          18219 non-null  float64
 20  L3_NO2_sensor_zenith_angle                           18219 non-null  float64
 21  L3_NO2_solar_azimuth_angle                           18219 non-null  float64
 22  L3_NO2_solar_zenith_angle                            18219 non-null  float64
 23  L3_NO2_stratospheric_NO2_column_number_density       18219 non-null  float64
 24  L3_NO2_tropopause_pressure                           18219 non-null  float64
 25  L3_NO2_tropospheric_NO2_column_number_density        18219 non-null  float64
 26  L3_O3_O3_column_number_density                       18219 non-null  float64
 27  L3_O3_O3_effective_temperature                       18219 non-null  float64
 28  L3_O3_cloud_fraction                                 18219 non-null  float64
 29  L3_O3_sensor_azimuth_angle                           18219 non-null  float64
 30  L3_O3_sensor_zenith_angle                            18219 non-null  float64
 31  L3_O3_solar_azimuth_angle                            18219 non-null  float64
 32  L3_O3_solar_zenith_angle                             18219 non-null  float64
 33  L3_CO_CO_column_number_density                       18219 non-null  float64
 34  L3_CO_H2O_column_number_density                      18219 non-null  float64
 35  L3_CO_cloud_height                                   18219 non-null  float64
 36  L3_CO_sensor_altitude                                18219 non-null  float64
 37  L3_CO_sensor_azimuth_angle                           18219 non-null  float64
 38  L3_CO_sensor_zenith_angle                            18219 non-null  float64
 39  L3_CO_solar_azimuth_angle                            18219 non-null  float64
 40  L3_CO_solar_zenith_angle                             18219 non-null  float64
 41  L3_HCHO_HCHO_slant_column_number_density             18219 non-null  float64
 42  L3_HCHO_cloud_fraction                               18219 non-null  float64
 43  L3_HCHO_sensor_azimuth_angle                         18219 non-null  float64
 44  L3_HCHO_sensor_zenith_angle                          18219 non-null  float64
 45  L3_HCHO_solar_azimuth_angle                          18219 non-null  float64
 46  L3_HCHO_solar_zenith_angle                           18219 non-null  float64
 47  L3_HCHO_tropospheric_HCHO_column_number_density      18219 non-null  float64
 48  L3_HCHO_tropospheric_HCHO_column_number_density_amf  18219 non-null  float64
 49  L3_CLOUD_cloud_base_height                           18219 non-null  float64
 50  L3_CLOUD_cloud_base_pressure                         18219 non-null  float64
 51  L3_CLOUD_cloud_fraction                              18219 non-null  float64
 52  L3_CLOUD_cloud_optical_depth                         18219 non-null  float64
 53  L3_CLOUD_cloud_top_height                            18219 non-null  float64
 54  L3_CLOUD_cloud_top_pressure                          18219 non-null  float64
 55  L3_CLOUD_sensor_azimuth_angle                        18219 non-null  float64
 56  L3_CLOUD_sensor_zenith_angle                         18219 non-null  float64
 57  L3_CLOUD_solar_azimuth_angle                         18219 non-null  float64
 58  L3_CLOUD_solar_zenith_angle                          18219 non-null  float64
 59  L3_CLOUD_surface_albedo                              18219 non-null  float64
 60  L3_AER_AI_absorbing_aerosol_index                    18219 non-null  float64
 61  L3_AER_AI_sensor_altitude                            18219 non-null  float64
 62  L3_AER_AI_sensor_azimuth_angle                       18219 non-null  float64
 63  L3_AER_AI_sensor_zenith_angle                        18219 non-null  float64
 64  L3_AER_AI_solar_azimuth_angle                        18219 non-null  float64
 65  L3_AER_AI_solar_zenith_angle                         18219 non-null  float64
 66  L3_SO2_SO2_column_number_density                     18219 non-null  float64
 67  L3_SO2_SO2_column_number_density_amf                 18219 non-null  float64
 68  L3_SO2_SO2_slant_column_number_density               18219 non-null  float64
 69  L3_SO2_absorbing_aerosol_index                       18219 non-null  float64
 70  L3_SO2_cloud_fraction                                18219 non-null  float64
 71  L3_SO2_sensor_azimuth_angle                          18219 non-null  float64
 72  L3_SO2_sensor_zenith_angle                           18219 non-null  float64
 73  L3_SO2_solar_azimuth_angle                           18219 non-null  float64
 74  L3_SO2_solar_zenith_angle                            18219 non-null  float64
dtypes: float64(71), int64(1), object(3)
memory usage: 10.6+ MB

In [20]:
# remove and create target labels for second try

second_try_train_labels = second_try_train[['target']]
second_try_train = second_try_train.drop(["target", "target_min", "target_max", "target_variance", "target_count"], axis=1)

In [22]:
# third approach: replace the NaN's with mean of the column it is in for train

third_try_train = dataDF_train
third_try_train = third_try_train.fillna(third_try_train.mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  after removing the cwd from sys.path.

In [23]:
# remove and create target labels for third try

third_try_train_labels = third_try_train[['target']]
third_try_train = third_try_train.drop(["target", "target_min", "target_max", "target_variance", "target_count"], axis=1)

In [24]:
# normalize train data

x = second_try_train.iloc[:,3:]
second_try_train.iloc[:,3:] = (x-x.min())/ (x.max() - x.min())

y = third_try_train.iloc[:,3:]
third_try_train.iloc[:,3:] = (y-y.min())/ (y.max() - y.min())

In [26]:
# convert dates to datetime

second_try_test['date'] = pd.to_datetime(second_try_test['Date'],format='%Y-%m-%d')
second_try_train['date'] = pd.to_datetime(second_try_train['Date'],format='%Y-%m-%d')

third_try_test['date'] = pd.to_datetime(third_try_test['Date'],format='%Y-%m-%d')
third_try_train['date'] = pd.to_datetime(third_try_train['Date'],format='%Y-%m-%d')

In [29]:
# cant realize "add holidays" idea, since the data is "spanning hundreds of cities across the globe" and different countries have different holidays
# can add other data like weekday or month

second_try_test['weekday'] = second_try_test['date'].dt.weekday
second_try_train['weekday'] = second_try_train['date'].dt.weekday

third_try_test['weekday'] = third_try_test['date'].dt.weekday
third_try_train['weekday'] = third_try_train['date'].dt.weekday

In [30]:
second_try_test['month'] = second_try_test['date'].dt.month
second_try_train['month'] = second_try_train['date'].dt.month

third_try_test['month'] = third_try_test['date'].dt.month
third_try_train['month'] = third_try_train['date'].dt.month

In [31]:
# change location id's to categories instead of objects ?